//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniSqlQuery.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MiniSqlQuery.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Could not populate with current connection string -  的本地化字符串。
        /// </summary>
        internal static string BindNewConnectionStringBuilder_Could_not_populate_with_current_connection_string___ {
            get {
                return ResourceManager.GetString("BindNewConnectionStringBuilder_Could_not_populate_with_current_connection_string_" +
                        "__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connected to &apos;{0}&apos; successfully. 的本地化字符串。
        /// </summary>
        internal static string Connected_to_0_successfully {
            get {
                return ResourceManager.GetString("Connected_to_0_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connection Failed 的本地化字符串。
        /// </summary>
        internal static string Connection_Failed {
            get {
                return ResourceManager.GetString("Connection_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connection Successful 的本地化字符串。
        /// </summary>
        internal static string Connection_Successful {
            get {
                return ResourceManager.GetString("Connection_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Database 的本地化字符串。
        /// </summary>
        internal static string Database {
            get {
                return ResourceManager.GetString("Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed connecting to &apos;{0}&apos;.{1}{2} 的本地化字符串。
        /// </summary>
        internal static string Failed_connecting_to_0_1_2 {
            get {
                return ResourceManager.GetString("Failed_connecting_to_0_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MINI SQL QUERY LICENSE
        ///PK Software - Paul Kohler
        ///paul@pksoftware.net
        ///
        ///----------------------------------------------------------------------
        ///
        ///Microsoft Public License (Ms-PL)
        ///
        ///This license governs use of the accompanying software. If you use the software, you accept this license. If you do not accept the license, do not use the software.
        ///
        ///1. Definitions
        ///
        ///The terms &quot;reproduce,&quot; &quot;reproduction,&quot; &quot;derivative works,&quot; and &quot;distribution&quot; have the same meaning here as under U.S. copyright law.
        ///
        ///A &quot;con [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string LicenseMiniSqlQuery {
            get {
                return ResourceManager.GetString("LicenseMiniSqlQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Messages 的本地化字符串。
        /// </summary>
        internal static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;Mini SQL Query Read Me&lt;/title&gt;
        ///	&lt;style type=&quot;text/css&quot;&gt;
        ///		h1, h2, h3, h4
        ///		{
        ///			font-family: Verdana;
        ///		}
        ///		blockquote, p, ul, ol, li
        ///		{
        ///			font-family: Verdana;
        ///			font-size: small;
        ///		}
        ///	&lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;h3&gt;
        ///		Mini SQL Query
        ///	&lt;/h3&gt;
        ///	&lt;blockquote&gt;
        ///		&lt;p&gt;
        ///			&quot;&lt;b&gt;Mini SQL Query&lt;/b&gt; from &lt;b&gt;PK Software&lt; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ReadMe {
            get {
                return ResourceManager.GetString("ReadMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reload Connection? 的本地化字符串。
        /// </summary>
        internal static string Reload_Connection {
            get {
                return ResourceManager.GetString("Reload_Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Changes? 的本地化字符串。
        /// </summary>
        internal static string Save_Changes {
            get {
                return ResourceManager.GetString("Save_Changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!-- 
        ///Copyright 2005-2009 Paul Kohler (http://pksoftware.net/MiniSqlQuery/). All rights reserved.
        ///This source code is made available under the terms of the Microsoft Public License (Ms-PL)
        ///http://minisqlquery.codeplex.com/license
        ///--&gt;
        ///&lt;SyntaxDefinition name = &quot;SQL&quot; extensions = &quot;.sql&quot;&gt;
        ///	&lt;Properties&gt;
        ///		&lt;Property name=&quot;LineComment&quot; value=&quot;--&quot;/&gt;
        ///	&lt;/Properties&gt;
        ///	&lt;Digits name = &quot;Digits&quot; bold = &quot;true&quot; italic = &quot;false&quot; color = &quot;Blue&quot;/&gt;
        ///	&lt;RuleSets&gt;
        ///		&lt;RuleSet ignorecase = &quot;true&quot;&gt;
        ///	 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string SqlModeXshd {
            get {
                return ResourceManager.GetString("SqlModeXshd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Table:  的本地化字符串。
        /// </summary>
        internal static string Table_colon {
            get {
                return ResourceManager.GetString("Table_colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Table: (none) 的本地化字符串。
        /// </summary>
        internal static string Table_none {
            get {
                return ResourceManager.GetString("Table_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tables 的本地化字符串。
        /// </summary>
        internal static string Tables {
            get {
                return ResourceManager.GetString("Tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Templates 的本地化字符串。
        /// </summary>
        internal static string TemplatesDirectoryName {
            get {
                return ResourceManager.GetString("TemplatesDirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The connection details have changed, do you want to save?
        /// 的本地化字符串。
        /// </summary>
        internal static string The_connection_details_have_changed__do_you_want_to_save {
            get {
                return ResourceManager.GetString("The_connection_details_have_changed__do_you_want_to_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The connections have changed, would you like to refresh the database connection? 的本地化字符串。
        /// </summary>
        internal static string The_connections_have_changed__would_you_like_to_refresh_the_database_connection {
            get {
                return ResourceManager.GetString("The_connections_have_changed__would_you_like_to_refresh_the_database_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View Data 的本地化字符串。
        /// </summary>
        internal static string ViewData {
            get {
                return ResourceManager.GetString("ViewData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View Data Error 的本地化字符串。
        /// </summary>
        internal static string ViewDataError {
            get {
                return ResourceManager.GetString("ViewDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Views 的本地化字符串。
        /// </summary>
        internal static string Views {
            get {
                return ResourceManager.GetString("Views", resourceCulture);
            }
        }
    }
}
