//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPINT {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SAPINT.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Bad authentication 的本地化字符串。
        /// </summary>
        internal static string Badauthentication {
            get {
                return ResourceManager.GetString("Badauthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Config is not exist 的本地化字符串。
        /// </summary>
        internal static string Configisnotexist {
            get {
                return ResourceManager.GetString("Configisnotexist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connection is not valid 的本地化字符串。
        /// </summary>
        internal static string Connectionisnotvalid {
            get {
                return ResourceManager.GetString("Connectionisnotvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could notfind Element{0} 的本地化字符串。
        /// </summary>
        internal static string CouldnotfindElement_0 {
            get {
                return ResourceManager.GetString("CouldnotfindElement_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not locate control record 的本地化字符串。
        /// </summary>
        internal static string Couldnotlocatecontrolrecord {
            get {
                return ResourceManager.GetString("Couldnotlocatecontrolrecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do not use primay key packaging without a custom function module 的本地化字符串。
        /// </summary>
        internal static string Donotuseprimaykeypackagingwithoutacustomfunctionmodule {
            get {
                return ResourceManager.GetString("Donotuseprimaykeypackagingwithoutacustomfunctionmodule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name is Empty 的本地化字符串。
        /// </summary>
        internal static string EmptyName {
            get {
                return ResourceManager.GetString("EmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error during SAPmemory allocation 的本地化字符串。
        /// </summary>
        internal static string ErrorduringSAPmemoryallocation {
            get {
                return ResourceManager.GetString("ErrorduringSAPmemoryallocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Message could not be found 的本地化字符串。
        /// </summary>
        internal static string Messagecouldnotbefound {
            get {
                return ResourceManager.GetString("Messagecouldnotbefound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Connection Assigned 的本地化字符串。
        /// </summary>
        internal static string NoConnectionAssigned {
            get {
                return ResourceManager.GetString("NoConnectionAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No data could be selected 的本地化字符串。
        /// </summary>
        internal static string Nodatacouldbeselected {
            get {
                return ResourceManager.GetString("Nodatacouldbeselected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Idoc number given 的本地化字符串。
        /// </summary>
        internal static string NoIdocnumbergiven {
            get {
                return ResourceManager.GetString("NoIdocnumbergiven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No variant o rvariant invalid 的本地化字符串。
        /// </summary>
        internal static string Novariantorvariantinvalid {
            get {
                return ResourceManager.GetString("Novariantorvariantinvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please define a selection or use the Max Rows property 的本地化字符串。
        /// </summary>
        internal static string PleasedefineaselectionorusetheMaxRowsproperty {
            get {
                return ResourceManager.GetString("PleasedefineaselectionorusetheMaxRowsproperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please make sure that the fields UserGroup and Name are filled correctly 的本地化字符串。
        /// </summary>
        internal static string PleasemakesurethatthefieldsUserGroupandNamearefilledcorrectly {
            get {
                return ResourceManager.GetString("PleasemakesurethatthefieldsUserGroupandNamearefilledcorrectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Query doesnot exists 的本地化字符串。
        /// </summary>
        internal static string Querydoesnotexists {
            get {
                return ResourceManager.GetString("Querydoesnotexists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Query locked 的本地化字符串。
        /// </summary>
        internal static string Querylocked {
            get {
                return ResourceManager.GetString("Querylocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Query must havea variant 的本地化字符串。
        /// </summary>
        internal static string Querymusthaveavariant {
            get {
                return ResourceManager.GetString("Querymusthaveavariant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SQL too long 的本地化字符串。
        /// </summary>
        internal static string SQLtoolong {
            get {
                return ResourceManager.GetString("SQLtoolong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System is Not Fount 的本地化字符串。
        /// </summary>
        internal static string SystemNotFount {
            get {
                return ResourceManager.GetString("SystemNotFount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The given code is not valid 的本地化字符串。
        /// </summary>
        internal static string Thegivencodeisnotvalid {
            get {
                return ResourceManager.GetString("Thegivencodeisnotvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Idoc data buffers width is 1000 bytes 的本地化字符串。
        /// </summary>
        internal static string TheIdocdatabufferswidthis1000bytes {
            get {
                return ResourceManager.GetString("TheIdocdatabufferswidthis1000bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The selection parameter {0} is obligatory and there is novalue provided 的本地化字符串。
        /// </summary>
        internal static string Theselectionparameter_0_isobligatoryandthereisnovalueprovided {
            get {
                return ResourceManager.GetString("Theselectionparameter_0_isobligatoryandthereisnovalueprovided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This is not a valid schema file 的本地化字符串。
        /// </summary>
        internal static string Thisisnotavalidschemafile {
            get {
                return ResourceManager.GetString("Thisisnotavalidschemafile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to convert {0} 的本地化字符串。
        /// </summary>
        internal static string Unabletoconvert_0 {
            get {
                return ResourceManager.GetString("Unabletoconvert_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User group does not exist 的本地化字符串。
        /// </summary>
        internal static string Usergroupdoesnotexist {
            get {
                return ResourceManager.GetString("Usergroupdoesnotexist", resourceCulture);
            }
        }
    }
}
